import Link from 'next/link';
import { demoOnion, networkEdges } from '@/lib/data';
import { getDemoMetrics } from '@/lib/metrics';
import { getEntries } from '@/lib/content';
import { Icon } from '@/components/icons';
import ResearchTerminal from '@/components/research-terminal';
import { StatusPill } from '@/components/site';

export default function Home(){
  const metrics = getDemoMetrics();
  const documents = getEntries('documents');
  const intelligence = getEntries('intelligence');
  return <main>
  <section className="hero"><div className="container hero-grid">
    <div><div className="eyebrow">Onion Service / Research Archive</div><h1 className="hero-title">Welcome to the hidden layer of the internet.</h1><p className="hero-copy">A fictional underground research portal for privacy, security engineering and open technical inquiry. Quiet by design. Dense with signal.</p><div className="cta-row"><Link href="/archive" className="btn btn-primary">Enter Archive <Icon name="arrow"/></Link><Link href="/network" className="btn btn-ghost">Explore Network <Icon name="globe"/></Link><Link href="/lab" className="btn btn-ghost">Open Lab <Icon name="arrow"/></Link></div></div>
    <div className="console-card"><div className="console-top"><div className="dots"><i className="dot"/><i className="dot"/><i className="dot"/></div><span className="mono muted small">SESSION // DEMO</span></div><div className="console-body"><div className="eyebrow">Onion Service</div><div className="address mono">{demoOnion}</div><div className="status-row"><span>STATUS</span><span className="status-value"><span className="signal"><i/> ONLINE</span></span></div><div className="status-row"><span>ROUTING</span><span className="status-value mono">SIMULATED</span></div><div className="status-row"><span>CHANNEL</span><span className="status-value mono">END-TO-END*</span></div><div className="status-row"><span>IDENTITY</span><span className="status-value mono">DEMO VERIFIED</span></div><p className="muted small" style={{marginBottom:0}}>* Visual/demo terminology. No real Tor circuit is exposed by this frontend.</p></div></div>
  </div></section>

  <section className="section"><div className="container"><div className="stat-grid"><div className="stat"><span className="stat-label">SERVICE STATE</span><span className="stat-number">OPERATIONAL</span></div><div className="stat"><span className="stat-label">SIMULATED NODES</span><span className="stat-number">{metrics.simulatedNodes}</span></div><div className="stat"><span className="stat-label">ARCHIVED ITEMS</span><span className="stat-number">{metrics.archivedItems}</span></div><div className="stat"><span className="stat-label">UPTIME</span><span className="stat-number">{metrics.uptime}</span></div></div></div></section>

  <section className="section"><div className="container"><div className="section-head"><div><div className="eyebrow">Latest intelligence</div><h2 className="section-title">Signal over noise.</h2></div><p className="section-copy">Fictional signal records designed to make the interface feel alive without exposing real services or real-world criminal infrastructure.</p></div><div className="grid-3">{intelligence.slice(0,3).map(item=><Link href={`/intelligence/${item.slug}`} className="card" key={item.id}><div className="eyebrow">{item.classification ?? item.state ?? 'SIGNAL'}</div><h3 className="card-title" style={{marginTop:8}}>{item.title}</h3><p className="card-copy">{item.description}</p><div className="meta">{item.tags.map(t=><span key={t} className="tag">{t}</span>)}</div></Link>)}</div></div></section>

  <section className="section"><div className="container grid-2"><div><div className="eyebrow">Research terminal</div><h2 className="section-title">Query the local index.</h2><p className="section-copy">Search the fictional document corpus without sending queries to a third-party provider.</p></div><ResearchTerminal entries={documents}/></div></section>

  <section className="section"><div className="container"><div className="section-head"><div><div className="eyebrow">Hidden archives</div><h2 className="section-title">Recent files.</h2></div><Link href="/archive" className="btn btn-ghost">View all <Icon name="arrow"/></Link></div><div className="archive-list">{documents.slice(0,4).map(doc=><Link href={`/documents/${doc.slug}`} className="archive-item" key={doc.id}><div className="doc-id mono">{doc.id}</div><div><h3 className="doc-title">{doc.title}</h3><p className="doc-desc">{doc.description}</p></div><div className="doc-date mono">{doc.date}</div></Link>)}</div></div></section>

  <section className="section"><div className="container grid-2"><div className="card"><div className="eyebrow">Manifesto</div><h2 className="section-title">Information does not disappear. It moves.</h2><p className="card-copy">Privacy is an engineering property, not a mood. Open-source systems deserve public scrutiny, and responsible security research requires clear boundaries.</p><Link href="/about" className="btn btn-ghost">Read the principles <Icon name="arrow"/></Link></div><div className="network-panel"><svg className="network-lines" viewBox="0 0 600 360" role="img" aria-label="Abstract simulated network graph"><g stroke="rgba(203,163,107,.18)" strokeWidth="1"><path d="M80 80L210 120 340 70 500 130 420 240 240 260 100 220Z"/><path d="M210 120L240 260M340 70L420 240M100 220L80 80M500 130L420 240"/></g><g><circle className="node core" cx="340" cy="70" r="18"/><circle className="node" cx="80" cy="80" r="11"/><circle className="node" cx="210" cy="120" r="12"/><circle className="node" cx="500" cy="130" r="10"/><circle className="node" cx="420" cy="240" r="14"/><circle className="node" cx="240" cy="260" r="11"/><circle className="node" cx="100" cy="220" r="9"/></g><g><circle className="node-dot" cx="340" cy="70" r="4"/><circle className="node-dot" cx="210" cy="120" r="3"/><circle className="node-dot" cx="420" cy="240" r="3"/></g></svg><div className="network-legend"><StatusPill text="SIMULATED NETWORK"/><span className="tag mono">{String(metrics.simulatedNodes).padStart(2, '0')} NODES</span><span className="tag mono">{String(networkEdges.length).padStart(2, '0')} EDGES</span></div></div></div></section>
</main> }
